### ISSUE TITLE
Общее значение верхнего маржина этого элемента и header-info можно вынести в верхний паддинг header

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#12]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/438db1415bc4bee0f14eb17ef9cbb7ae3b69eddf/css/blocks/header.css#L7

**Comment by StepanOmelchenko** [comment]
Добавил header паддинг сверху, для info и logo убрал верхнии маржины
