### ISSUE TITLE
Это скорее всего ошибка дизайнера, не должно быть позиционирования у заголовков

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#13]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/438db1415bc4bee0f14eb17ef9cbb7ae3b69eddf/css/blocks/rates.css#L8

**Comment by StepanOmelchenko** [comment]
убрал позиционирование у заголовка
