### ISSUE TITLE
Лучше перенести маржин для news

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#14]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/438db1415bc4bee0f14eb17ef9cbb7ae3b69eddf/css/blocks/pagination.css#L2

**Comment by StepanOmelchenko** [comment]
переименовал класс news для контейнера в main-news (чтоб не выделялся) и на него повесил маржин вниз, с пагинации убрал
