### ISSUE TITLE
Убрать позиционирование и максимальную высоту. 

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#18]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/438db1415bc4bee0f14eb17ef9cbb7ae3b69eddf/css/blocks/reviews.css#L31

**Comment by StepanOmelchenko** [comment]
Убрал позиционирование и высоту, выровнял по центру за счет паддинга родителя
