### ISSUE TITLE
Убрать фиксированную высоту элемента и сделать высоту блока за счет внутренних отступов

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#19]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/438db1415bc4bee0f14eb17ef9cbb7ae3b69eddf/css/blocks/reviews.css#L16

**Comment by StepanOmelchenko** [comment]
Убрал фиксированную высоту, выровнял содержимое за счет падинга
