### ISSUE TITLE
Для всех блоков, у которых прямые потомки имеют свойство float нужно добавлять класс clearfix

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#2]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/e0108fe227fe19424ae68602b26c66afbaf7ceb1/index.html#L28

**Comment by igosheva** [comment]
Пройдись по всей странице и добавь для всех блоков, у которых дети с float класс clearfix

**Comment by StepanOmelchenko** [comment]
добавил, у меня пока float есть только в header и sidebar с main-body тоже float разводит. Конечно планирую расширить его применение, вроде идею с clearfix понял
