### ISSUE TITLE
Добавить паддинг справа, а также убрать опасити http://joxi.ru/l2ZQWwds8ybMOm

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#21]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/438db1415bc4bee0f14eb17ef9cbb7ae3b69eddf/comments.html#L170

**Comment by StepanOmelchenko** [comment]
Добавил паддинг справа, убрал опасити
