### ISSUE TITLE
Помимо этого свойства еще обязательно нужно указывать background-position и background-repeat

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#23]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/be2716ff0a6ebc8bfa975be873670ae164d58f84/css/blocks/intro.css#L5

**Comment by StepanOmelchenko** [comment]
добавил
 background-position: center;
 background-repeat: no-repeat;
