### ISSUE TITLE
Убрать фиксированную высоту и ширину и сделать высоту и ширину за счет паддингов

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#24]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/be2716ff0a6ebc8bfa975be873670ae164d58f84/css/blocks/header.css#L52

**Comment by StepanOmelchenko** [comment]
Убрал фиксированную высоту-ширину, отцентровал за счет padding
