### ISSUE TITLE
Сейчас при ховере появляется рамка и увеличивает высоту и ширину элемента, из-за этого элемент дергается. Нужно добавить прозрачные бордеры заранее)

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#25]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/be2716ff0a6ebc8bfa975be873670ae164d58f84/css/blocks/rates.css#L23

**Comment by StepanOmelchenko** [comment]
Добавил в элемент
 border: solid 1px transparent;
По ховеру добавляю цвет
