### ISSUE TITLE
Лого лучше вставить в явном виде через svg в код.

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#29]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/5f5eb71ea93d74be417f8854627a36ca8cc01fd9/sites/burger/scss/blocks/first.scss#L21

**Comment by StepanOmelchenko** [comment]
вставил в виде кода, картинку удалил
