### ISSUE TITLE
По факту можно и без этой обортки обойтись

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#31]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/5f5eb71ea93d74be417f8854627a36ca8cc01fd9/sites/burger/index.html#L147

**Comment by StepanOmelchenko** [comment]
Убрал лишнюю обертку, сделал затенение через псевдо элемент, а текста повесил абсолютом поверх.
