### ISSUE TITLE
У этого свойства нет такого значения, но есть align-items: flex-start;

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#33]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/5f5eb71ea93d74be417f8854627a36ca8cc01fd9/sites/burger/scss/blocks/sixth.scss#L52

**Comment by StepanOmelchenko** [comment]
Поменял на flex-start
