### ISSUE TITLE
Убрать высоту и маржины и задать просто для fifth__container паддинги со всех сторон

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#34]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/46075dc32ed2090f275cec9ce12fa6ba516dbf3e/sites/burger/scss/blocks/fifth.scss#L114

**Comment by StepanOmelchenko** [comment]
Если задаю fifth__container падинги  со всех сторон, то он перестает полностью скрываться. Убрал у .fifth__container-inner высоту и отступы, растянул на родителя и задал падинги со всех сторон
