### ISSUE TITLE
Из-за флекса у first__header этот элемент становится высотой родителя. Нужно чтобы кликабельная область была только в высоту и ширину гамбургера

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#35]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/46075dc32ed2090f275cec9ce12fa6ba516dbf3e/sites/burger/index.html#L46

**Comment by StepanOmelchenko** [comment]
Убрал вертикальные отступы в header всем элементам и дал им align-atems center на родителя. Гамбургер перестало тянуть на всю вертикаль и остальные тоже все на места встали норм
