### ISSUE TITLE
Отступы громадные, должны быть меньше)

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#36]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/46075dc32ed2090f275cec9ce12fa6ba516dbf3e/sites/burger/scss/blocks/fourth.scss#L44

**Comment by StepanOmelchenko** [comment]
Поставил 20px по макету вроде норм теперь
