### ISSUE TITLE
А почему ты не вкладываешь друг в друга элементы? Куда приятней вложить все элементы в один блок, и так читается как-то легче)

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#37]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/46075dc32ed2090f275cec9ce12fa6ba516dbf3e/sites/burger/scss/blocks/fourth.scss#L1

**Comment by StepanOmelchenko** [comment]
Переделываю почучуть
