### ISSUE TITLE
Нужно за счет (например) внутренних отступов захватить в высоту этого блока элементы "состав" и "каллогии"

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#39]
![2018-02-06_00-14-55](https://user-images.githubusercontent.com/22238895/35829206-290e0e3e-0ad3-11e8-9302-c3a7a16362f3.png)
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/bb7b3e0727cc2a3abc8a6bd74a3e5488ab20a78b/sites/burger/index.html#L125

**Comment by StepanOmelchenko** [comment]
Добавил паддингов сверху и снизу, составу и калории убрал отрецательное позиционирование. Все в контейнере теперь
