### ISSUE TITLE
Шрифт не по макету. И размер шрифта доллара должен быть меньше

### ISSUE THREAD

**Issue by igosheva** [StepanOmelchenko/StepanOmelchenko.github.io#6]
https://github.com/StepanOmelchenko/StepanOmelchenko.github.io/blob/e0108fe227fe19424ae68602b26c66afbaf7ceb1/css/style.css#L191

**Comment by StepanOmelchenko** [comment]
Скачал еще один шрифт roboto regular, подключил его. Первую букву уменьшил через псевдокласс.
